sudo: required

language: java
jdk:
    - openjdk8
node_js:
    - "11"

addons:
    chrome: stable

before_install:
    - nvm install 11.0.0
    - npm install -g npm
    - cd src/main/angular
    - npm ci
    - npm run build -- --aot --prod
    - mkdir ../resources/static/
    - cp -r dist/* ../resources/static/
    - cd ../../..
    - chmod +x mvnw

before_script:
    - cd src/main/angular
    - npm run lint
    - npm run test
    - npm run e2e
    - cd ../../..

deploy:
    provider: heroku
    buildpack: java
    skip_cleanup: true
    app: frais-divers-co
    api_key: $HEROKU_KEY
    on:
        branch: master
