sudo: required
dist: trusty

language: java
jdk:
  - oraclejdk8
node_js:
- "lts/*"

apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable

before_install:
  - nvm install 7
  - cd src/main/angular
  - npm install
  - npm run build -- --aot --prod
  - mkdir ../java/src/main/webapp/
  - cp -r dist/* ../java/src/main/webapp/
  - cd ../../..
  - chmod +x mvnw

before_script:
  - cd ../angular
  - npm run lint
  - npm run test -- --watch=false
  - npm run e2e
  - cd ../../..

deploy:
  provider: heroku
  buildpack: java
  skip_cleanup: true
  app: frais-divers-co
  api_key: $HEROKU_KEY
  on:
    branch: master
